[IDF-43] feat: HTTP API integration and other improvements
first-line-outsourcing/flo.sls pull request #94
Opened 2021-05-28 12:53 UTC by khoroshilov-flo

CHANGELOG:
- Add HTTP API usage examples
- Add HTTP REST API usage examples
- Add custom authorizer examples
- Update `serverless` and other related dependencies
- Change CRLF to LF in `.editorconfig`
- Update media-info lambda to use HTTP API event
- Update errors/ section
- Update helper/ section
- Update CORS related recourses for REST API
- Make small changes to the serverless config to work with new version of `serverless`
- Fix `deploy:local` cmd to work with new versions offline plugin
- Update README

2021-05-28 12:55 UTC, khoroshilov-flo commented
I will check errors in circle CI

2021-05-31 10:21 UTC, azhivaeva-flo requested changes

2021-05-31 10:21 UTC, azhivaeva-flo commented on api/rest-api/handler.ts
> +import { errorHandler } from '../../helper/rest-api/error-handler';
Replace with @helper/rest-api/error-handler

2021-05-31 10:21 UTC, azhivaeva-flo commented on api/rest-api/handler.ts
> +import { APIGatewayLambdaEvent } from '../../interfaces/api-gateway-lambda.interface';
Replace with @interfaces/api-gateway-lambda.interface

2021-05-31 10:21 UTC, azhivaeva-flo commented on package.json
> +    "@workflowwin/iconik-api": "2.2.1",
We don't need iconik-api in this project.
win.sls has it and should be used for WIN projects as a template

2021-05-31 10:23 UTC, azhivaeva-flo commented
> I will check errors in circle CI

If you remove the iconik-api package, it will solve problems with CI 🙂

2021-05-31 14:13 UTC, azhivaeva-flo approved these changes
Good job! 🙂

2021-05-31 14:57 UTC, zaikin-andrew approved these changes

2021-06-02 05:44 UTC, azhivaeva-flo commented
@khoroshilov-flo I noticed that this version of Serverless has problems with environment variables like `${file(env.yml):${opt:stage, self:provider.stage}.CLIENT}` after deploy. Could you check it, please?

2021-06-02 21:30 UTC, khoroshilov-flo commented
> @khoroshilov-flo I noticed that this version of Serverless has problems with environment variables like `${file(env.yml):${opt:stage, self:provider.stage}.CLIENT}` after deploy. Could you check it, please?

No problems after deploy
![image](https://user-images.githubusercontent.com/69796613/120554812-e1128c80-c402-11eb-8ff1-58aa9d3adbf3.png)

2021-06-03 09:08 UTC, emahota-flo approved these changes

2021-06-03 19:31 UTC, merged